#!/usr/bin/env bash
# Printer Nanny -- site agent installer.
#
# Installs the agent into a venv and runs it as a systemd service. Designed to be
# piped from the central server with the enrollment values baked in:
#
#   curl -fsSL https://CENTRAL/install-agent.sh | sudo bash -s -- \
#     --central-url https://CENTRAL --agent-id 12 --api-key pn_xxxxx
#
# Re-running upgrades in place. Subnets, SNMP, and intervals come from the central
# UI -- they are NOT configured here.
set -euo pipefail

CENTRAL_URL=""
AGENT_ID=""
API_KEY=""
VERIFY_TLS="true"
PIP_SOURCE="git+https://github.com/your-org/printer-nanny.git#subdirectory=agent"
INSTALL_DIR="/opt/printer-nanny"
CONFIG_DIR="/etc/printer-nanny"
SERVICE_USER="printer-nanny"
PYTHON_BIN="python3"

while [ $# -gt 0 ]; do
  case "$1" in
    --central-url) CENTRAL_URL="$2"; shift 2 ;;
    --agent-id)    AGENT_ID="$2"; shift 2 ;;
    --api-key)     API_KEY="$2"; shift 2 ;;
    --verify-tls)  VERIFY_TLS="$2"; shift 2 ;;
    --pip-source)  PIP_SOURCE="$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="$2"; shift 2 ;;
    --service-user) SERVICE_USER="$2"; shift 2 ;;
    --python)      PYTHON_BIN="$2"; shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

die() { echo "error: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root (use sudo)"
[ -n "$CENTRAL_URL" ] || die "--central-url is required"
[ -n "$AGENT_ID" ] || die "--agent-id is required"
[ -n "$API_KEY" ] || die "--api-key is required"
case "$PIP_SOURCE" in
  *your-org*) die "pip source still points at the 'your-org' placeholder. Pass --pip-source with your real repo, or set it in the central UI (Settings -> Agent install)." ;;
esac
command -v "$PYTHON_BIN" >/dev/null 2>&1 || die "$PYTHON_BIN not found; install Python 3.9+"

# Try to install missing prerequisites automatically. We can't do this in the
# Windows installer's spirit (winget), but apt / dnf / yum cover almost every
# Linux box an MSP would deploy this on.
install_pkgs() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq >/dev/null 2>&1 || true
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@" >/dev/null
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y -q "$@" >/dev/null
  elif command -v yum >/dev/null 2>&1; then
    yum install -y -q "$@" >/dev/null
  else
    return 1
  fi
}

# Debian 12 / Ubuntu 24.04 split `ensurepip` into its own apt package and the
# venv create silently leaves an empty .venv/ behind that breaks every later run.
# Auto-install python3-venv (or the distro equivalent) so the operator doesn't
# have to know which package they need.
if ! "$PYTHON_BIN" -c "import ensurepip" >/dev/null 2>&1; then
  PKG_VER="$(basename "$PYTHON_BIN" | grep -oE '[0-9]+\.[0-9]+' | head -1)"
  CANDIDATES=()
  [ -n "$PKG_VER" ] && CANDIDATES+=("python${PKG_VER}-venv")
  CANDIDATES+=("python3-venv")
  echo "==> Python venv support missing; installing ${CANDIDATES[*]}"
  if ! install_pkgs "${CANDIDATES[@]}"; then
    die "Auto-install failed (no apt/dnf/yum, or install errored). Install one of: ${CANDIDATES[*]} and re-run."
  fi
  "$PYTHON_BIN" -c "import ensurepip" >/dev/null 2>&1 || \
    die "venv support still missing after package install. Check that ${CANDIDATES[*]} matches $PYTHON_BIN."
fi

echo "==> Printer Nanny agent installer"
echo "    central : $CENTRAL_URL"
echo "    agent   : #$AGENT_ID"
echo "    install : $INSTALL_DIR"

# Service account (system user, no login).
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  echo "==> creating service user '$SERVICE_USER'"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null \
    || useradd --system --shell /bin/false "$SERVICE_USER"
fi

# venv + agent. If a previous run left a broken .venv/ behind (e.g. missing
# python3-venv at the time), `pip` won't be there -- wipe and recreate instead
# of looping forever on the same partial directory.
echo "==> installing agent into $INSTALL_DIR (pip source: $PIP_SOURCE)"
mkdir -p "$INSTALL_DIR"
if [ ! -x "$INSTALL_DIR/.venv/bin/pip" ]; then
  if [ -d "$INSTALL_DIR/.venv" ]; then
    echo "    .venv exists but pip is missing -- recreating"
    rm -rf "$INSTALL_DIR/.venv"
  fi
  "$PYTHON_BIN" -m venv "$INSTALL_DIR/.venv"
fi
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade "$PIP_SOURCE"

# Config file (secret -- 0600).
echo "==> writing $CONFIG_DIR/agent.toml"
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_DIR/agent.toml" <<EOF
# Generated by install-agent.sh -- operational settings are managed in the central UI.
central_url = "$CENTRAL_URL"
agent_id = $AGENT_ID
api_key = "$API_KEY"
verify_tls = $VERIFY_TLS
EOF
chown -R "$SERVICE_USER" "$INSTALL_DIR" "$CONFIG_DIR"
chmod 600 "$CONFIG_DIR/agent.toml"

# systemd service.
if command -v systemctl >/dev/null 2>&1; then
  echo "==> installing systemd service"
  cat > /etc/systemd/system/printer-nanny-agent.service <<EOF
[Unit]
Description=Printer Nanny site agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Environment=PRINTER_NANNY_CONFIG=$CONFIG_DIR/agent.toml
ExecStart=$INSTALL_DIR/.venv/bin/printer-nanny-agent run
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now printer-nanny-agent
  echo "==> done. Status:"
  systemctl --no-pager --lines=5 status printer-nanny-agent || true
  echo
  echo "Logs: journalctl -u printer-nanny-agent -f"
else
  echo "!! systemd not found -- start the agent manually:"
  echo "   PRINTER_NANNY_CONFIG=$CONFIG_DIR/agent.toml $INSTALL_DIR/.venv/bin/printer-nanny-agent run"
fi
