#!/usr/bin/env bash
# Printer Nanny — one-line Docker Compose installer.
#
# Pulled from a checkout:
#   bash deploy/install.sh [--demo] [--branch main] [--dir printer-nanny]
#
# Pulled from the network (this is the advertised one-liner):
#   curl -fsSL https://raw.githubusercontent.com/stephenthecold/printer-nanny/main/deploy/install.sh | bash
#
# What it does, idempotently:
#   1. Clones (or updates) the repo into ./printer-nanny (skipped if already in a checkout).
#   2. Generates .env with a strong SECRET_KEY if it doesn't exist.
#   3. Runs `docker compose up -d --build`.
#   4. Waits for the API to answer /healthz.
#   5. With --demo, runs the destructive demo seed AFTER confirming the user wants it.
#
# Re-running is safe: it never overwrites your .env, never drops your data
# (unless --demo is passed), and just pulls the latest image / restarts services.
set -euo pipefail

REPO_URL="${PRINTER_NANNY_REPO:-https://github.com/stephenthecold/printer-nanny.git}"
BRANCH="${PRINTER_NANNY_BRANCH:-main}"
INSTALL_DIR=""
DEMO=0
PORT=8080
BUILD_FLAG="--build"

while [ $# -gt 0 ]; do
  case "$1" in
    --demo)        DEMO=1; shift ;;
    --dir)         INSTALL_DIR="$2"; shift 2 ;;
    --branch)      BRANCH="$2"; shift 2 ;;
    --repo-url)    REPO_URL="$2"; shift 2 ;;
    --port)        PORT="$2"; shift 2 ;;
    --no-build)    BUILD_FLAG=""; shift ;;
    -h|--help)
      sed -n '2,18{/^#/{s/^# \{0,1\}//;p;}}' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

die()  { echo "error: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "'$1' not found in PATH"; }

need docker
docker compose version >/dev/null 2>&1 \
  || die "Docker Compose v2 plugin missing (install 'docker-compose-plugin')."

in_repo() { [ -f docker-compose.yml ] && [ -d central ] && [ -f deploy/Dockerfile ]; }

# Use an existing checkout if the user piped us from inside one; otherwise clone.
if [ -z "$INSTALL_DIR" ] && in_repo; then
  echo "==> using current checkout: $(pwd)"
else
  TARGET="${INSTALL_DIR:-printer-nanny}"
  if [ -d "$TARGET/.git" ]; then
    echo "==> updating existing checkout at $TARGET"
    need git
    git -C "$TARGET" fetch --quiet origin "$BRANCH"
    git -C "$TARGET" checkout --quiet "$BRANCH"
    git -C "$TARGET" pull --quiet --ff-only
  else
    need git
    echo "==> cloning $REPO_URL (branch $BRANCH) → $TARGET"
    git clone --quiet --branch "$BRANCH" --depth 1 "$REPO_URL" "$TARGET"
  fi
  cd "$TARGET"
fi

# Generate .env with a strong SECRET_KEY on first run; leave existing files alone.
if [ ! -f .env ]; then
  echo "==> generating .env with a fresh SECRET_KEY"
  if command -v openssl >/dev/null 2>&1; then
    SECRET=$(openssl rand -base64 48 | tr -d '\n')
  else
    SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '\n')
  fi
  umask 077
  cat > .env <<EOF
# Generated by deploy/install.sh — do not commit. Rotate by deleting and re-running.
SECRET_KEY=$SECRET
EOF
else
  echo "==> .env already present; leaving it alone"
fi

echo "==> docker compose up -d $BUILD_FLAG"
docker compose up -d $BUILD_FLAG

echo "==> waiting for the API on http://localhost:${PORT}/healthz"
DEADLINE=$(( $(date +%s) + 180 ))
until curl -fsS "http://localhost:${PORT}/healthz" >/dev/null 2>&1; do
  if [ "$(date +%s)" -ge "$DEADLINE" ]; then
    echo
    echo "API didn't respond within 3 minutes. Recent logs:"
    docker compose logs --tail=40 api || true
    die "startup timed out"
  fi
  sleep 2
done

if [ "$DEMO" -eq 1 ]; then
  echo
  echo "!! --demo will DROP all tables and reseed with fake clients/printers."
  if [ -t 0 ]; then
    read -r -p "   Type 'yes' to continue: " ans
    [ "$ans" = "yes" ] || die "aborted"
  fi
  echo "==> seeding demo data"
  docker compose exec -T api python -m central.seed
fi

cat <<EOF

  Printer Nanny is up at http://localhost:${PORT}
  Login: admin / admin   ← change this password immediately
                           (Settings → Users, or /manage)

  Logs:    docker compose logs -f api worker
  Stop:    docker compose down
  Update:  re-run this installer (preserves your .env and data)

EOF
