"""Baseline schema — create all tables from the ORM metadata.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-05
"""

from alembic import op

from central.db import Base
import central.models  # noqa: F401  (register all tables on Base.metadata)

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Greenfield baseline: the ORM metadata is the source of truth, so create the
    # full schema directly. Subsequent changes use autogenerated incremental revisions.
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
