"""login_attempts table + users.must_change_password

Revision ID: 0042_auth_hardening
Revises: 0040_collector_redundancy
Create Date: 2026-08-03

Two halves of the same change (see central/ratelimit.py and central/seed.py):

* ``login_attempts`` -- one row per FAILED local sign-in, in a "user" scope and
  an "ip" scope. Operational state for the throttle, deliberately separate from
  ``audit_log``: if the throttle counted audit rows, trimming the audit log
  would unlock every account at once.
* ``users.must_change_password`` -- set by the first-run bootstrap, whose admin
  password is now generated and printed to the container log once. The log keeps
  that password forever, so the flag is what retires it.

Added conditionally for the same reason as 0027-0033 and 0041: revision 0001 is
``Base.metadata.create_all()``, so a fresh database already has both from the ORM
metadata by the time this migration runs, while an upgraded one does not.

The indexes are declared in ``models.LoginAttempt.__table_args__`` as well as
here. That duplication is the rule in this repo, not an oversight: an index that
exists only in a migration is silently absent on every fresh install, because
0001 builds the schema from the ORM metadata.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0042_auth_hardening"
down_revision = "0040_collector_redundancy"
branch_labels = None
depends_on = None

TABLE = "login_attempts"
USERS = "users"
COLUMN = "must_change_password"
INDEXES = (
    ("ix_login_attempts_scope_key_ts", ["scope", "key", "ts"]),
    ("ix_login_attempts_ts", ["ts"]),
)


def _inspector():
    return sa.inspect(op.get_bind())


def _tables() -> set:
    return set(_inspector().get_table_names())


def _columns(table: str) -> set:
    return {c["name"] for c in _inspector().get_columns(table)}


def _indexes(table: str) -> set:
    return {i["name"] for i in _inspector().get_indexes(table)}


def upgrade() -> None:
    if TABLE not in _tables():
        op.create_table(
            TABLE,
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
            sa.Column("scope", sa.String(length=8), nullable=False),
            sa.Column("key", sa.String(length=200), nullable=False),
        )
    existing = _indexes(TABLE)
    for name, columns in INDEXES:
        if name not in existing:
            op.create_index(name, TABLE, columns)

    if COLUMN not in _columns(USERS):
        # server_default false() so the rows that already exist are NOT locked
        # out of the dashboard by an upgrade -- only accounts the bootstrap
        # creates from here on carry the requirement.
        op.add_column(
            USERS,
            sa.Column(COLUMN, sa.Boolean(), nullable=False,
                      server_default=sa.false()),
        )


def downgrade() -> None:
    """Reverses cleanly, including on a database where 0001 built the table.

    Dropping ``login_attempts`` here is not the destructive-downgrade defect this
    repo has been bitten by (a downgrade deleting operator settings). Every row
    in it is a transient counter that expires within minutes on its own and is
    regenerated by the next failed sign-in; there is nothing an operator entered
    and nothing that could be missed. The audit trail of those same failures
    lives in ``audit_log`` and is not touched.
    """
    if COLUMN in _columns(USERS):
        op.drop_column(USERS, COLUMN)
    if TABLE in _tables():
        existing = _indexes(TABLE)
        for name, _cols in INDEXES:
            if name in existing:
                op.drop_index(name, table_name=TABLE)
        op.drop_table(TABLE)
