"""Redeem a claim code for real agent credentials, once, at first start.

The operator hands the site a short-lived code instead of an API key. This
module trades that code for an ``agent_id`` + ``api_key`` and writes them into
the config file, so nothing long-lived ever had to travel.

Persisting the result is not an optimisation, it is the whole contract: a claim
code is single-use, so an agent that redeemed one and then forgot the answer
would fail permanently on its next restart. The write is atomic (temp file +
replace) for the same reason -- a half-written config after a power cut at
exactly the wrong moment would be indistinguishable from never having enrolled,
except that the code is now spent.
"""

from __future__ import annotations

import json
import logging
import os
import socket
import stat
import tempfile
from typing import Optional
from urllib import error as urlerror
from urllib import request as urlrequest

log = logging.getLogger(__name__)

REGISTER_PATH = "/api/v1/agents/register"


class EnrollmentError(RuntimeError):
    """Enrollment failed in a way the operator has to act on."""


def _hostname() -> str:
    try:
        return socket.gethostname()
    except OSError:  # pragma: no cover - hostname lookups effectively never fail
        return ""


def redeem_claim_code(
    central_url: str,
    claim_code: str,
    *,
    verify_tls: bool = True,
    version: Optional[str] = None,
    timeout: float = 30.0,
) -> dict:
    """POST the claim code to central. Returns the decoded response dict.

    Uses urllib rather than the agent's httpx client because this runs before
    the agent has an identity, and the client is built around having one. It is
    also a single blocking call at process start, so there is nothing for async
    to overlap with.
    """
    url = central_url.rstrip("/") + REGISTER_PATH
    payload = json.dumps({
        "claim_code": claim_code,
        "hostname": _hostname(),
        "version": version,
    }).encode("utf-8")
    req = urlrequest.Request(
        url, data=payload, headers={"Content-Type": "application/json"}, method="POST"
    )

    context = None
    if not verify_tls:
        import ssl

        # Mirrors the agent's existing verify_tls=False escape hatch for
        # self-signed on-prem certs. Off by default, and never silently.
        context = ssl._create_unverified_context()
        log.warning("TLS verification disabled for enrollment (verify_tls=false)")

    try:
        with urlrequest.urlopen(req, timeout=timeout, context=context) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urlerror.HTTPError as exc:
        if exc.code == 401:
            raise EnrollmentError(
                "claim code rejected: it is unknown, expired, or already used. "
                "Mint a fresh one from Agents -> Claim code."
            ) from exc
        raise EnrollmentError(f"central returned HTTP {exc.code} during enrollment") from exc
    except urlerror.URLError as exc:
        raise EnrollmentError(f"could not reach {url}: {exc.reason}") from exc

    missing = [k for k in ("agent_id", "api_key") if not body.get(k)]
    if missing:
        raise EnrollmentError(
            f"enrollment response missing {', '.join(missing)} -- refusing to continue"
        )
    return body


def persist_credentials(config_path: str, creds: dict) -> None:
    """Write agent_id / api_key into the TOML config, atomically.

    Deliberately hand-rolled rather than round-tripping a TOML library: the
    agent depends on a *reader* only (tomllib/tomli), and adding a writer to
    every install just to append two scalars is a poor trade. Existing
    ``agent_id`` / ``api_key`` / ``claim_code`` lines are dropped so a re-run
    cannot leave two conflicting values or a spent code behind.
    """
    lines = []
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as fp:
            for line in fp:
                key = line.split("=", 1)[0].strip()
                if key in ("agent_id", "api_key", "claim_code"):
                    continue
                lines.append(line.rstrip("\n"))

    lines.append(f"agent_id = {int(creds['agent_id'])}")
    # TOML basic string. The key is generated by central from a urlsafe
    # alphabet, so there is nothing to escape, but quote defensively anyway.
    api_key = str(creds["api_key"]).replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'api_key = "{api_key}"')

    directory = os.path.dirname(config_path) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".agent.toml.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fp:
            fp.write("\n".join(lines) + "\n")
        # The file now holds a live credential: owner-only before it is visible
        # under its final name, not after.
        os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp, config_path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    log.info("enrolled as agent %s; credentials written to %s",
             creds["agent_id"], config_path)
